Repository TheBenKnee/CS-472-Senior-Design-Project, pull requests merged in 2023-04, with the labels that each got.

#85 Map Level System
  Assets/Art/MinifolksVillagers/Outline/FlippedMiniNobleMan.png.meta
  Assets/Resources/stairs.png
  Assets/Resources/stairs.png.meta
  Assets/Scripts/GameManagers/Tiles/BaseTile_VM.cs
  Assets/Scripts/TileMapDemoScripts/BaseTile.cs
  Assets/Scripts/TileMapDemoScripts/CameraManager.cs
  Assets/Scripts/TileMapDemoScripts/CameraManager.cs.meta
  Assets/Scripts/TileMapDemoScripts/CharacterManager.cs
  Assets/Scripts/TileMapDemoScripts/CharacterManager.cs.meta
  Assets/Scripts/TileMapDemoScripts/Level.cs
  Assets/Scripts/TileMapDemoScripts/Level.cs.meta
  Assets/Scripts/TileMapDemoScripts/MapManager.cs
  Assets/Scripts/TileMapDemoScripts/PathFinding.cs
  Assets/Scripts/TileMapDemoScripts/Player.cs
  Assets/Tests/EditMode/BaseTile/RockTileTest.cs
Labels: new feature

#84 Added Hunger Timer
  Assets/Art/MinifolksVillagers/Outline/FlippedMiniOldWoman.png.meta
  Assets/Prefabs/Pawn2.prefab
  Assets/Prefabs/Pawn2.prefab.meta
  Assets/Scenes/ConnorLaborOrder.unity
  Assets/Scriptable Objects/Entities/Pawn2.asset
  Assets/Scriptable Objects/Entities/Pawn2.asset.meta
  Assets/Scriptable Objects/PrefabList.asset
  Assets/Scripts/GameManagers/LaborOrderManager.cs
  Assets/Scripts/LaborOrders/LaborOrder_Woodcut.cs
  Assets/Scripts/NPC/HungerTimer.cs
  Assets/Scripts/NPC/HungerTimer.cs.meta
  Assets/Scripts/NPC/Pawn.cs
  Assets/Scripts/TileMapDemoScripts/MapManager.cs
  Assets/Tests/EditMode/LaborOrderManager/LaborOrderManagerTest.cs
  Assets/Tests/EditMode/LaborOrderManager/LaborOrderManagerTest.cs.meta
Labels: new feature

#88 COL-103-Global storage chest system
  Assets/Scripts/Inventory/Chest.cs
  Assets/Scripts/Inventory/GlobalStorage.cs
Labels: new feature

#92 [COL-104 | COL-105] - Amended global storage + global storage tests
  Assets/Scripts/Inventory/GlobalStorage.cs
  Assets/Tests/EditMode/Inventory/GlobalStorage.cs
  Assets/Tests/EditMode/Inventory/GlobalStorage.cs.meta
Labels: feature expansion, unit tests

#90 LaborOrder Panel Adjustments
  Assets/Resources/prefabs/laborText_LaborOrder.prefab
  Assets/Resources/prefabs/laborText_LaborOrder.prefab.meta
  Assets/Resources/prefabs/pawnButton_LaborOrder.prefab
  Assets/Resources/prefabs/pawnButton_LaborOrder.prefab.meta
  Assets/Resources/prefabs/pawnText_LaborOrder.prefab
  Assets/Resources/prefabs/pawnText_LaborOrder.prefab.meta
  Assets/Scenes/LaborOrderPanel.unity
  Assets/Scripts/GameManagers/GameManager.cs
  Assets/Scripts/GameManagers/LaborOrderManager_VM.cs
  Assets/Scripts/GameManagers/Pawn_VM.cs
  Assets/Scripts/UI/Game.cs
  Assets/Scripts/UI/Game.cs.meta
  Assets/Scripts/UI/LaborOrderPanelManager.cs
  Assets/Scripts/UI/PawnButton.cs
Labels: feature expansion

#94 Resolved issue with GridManager.cs CreateLevel Method
  Assets/Scripts/GameManagers/GridManager.cs
Labels: bug fix

#95 CameraManager added to CombinedManagers Scene
  Assets/Scripts/GameManagers/CameraManager.cs
  Assets/Scripts/GameManagers/CameraManager.cs.meta
  Assets/Scripts/GameManagers/GameManager.cs
  Assets/Scripts/GameManagers/GridManager.cs
  Assets/Scripts/GameManagers/InputManager.cs
  Assets/Scripts/TileMapDemoScripts/CameraManager.cs
  Assets/Scripts/TileMapDemoScripts/MapManager.cs
Labels: new feature

#96 Finalized Main Menu
  Assets/Art/Characters/MinifolksVillagers/Outline/FlippedMiniNobleMan.png.meta
  Assets/Packages/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/UI/MainMenuManager.cs
  Assets/Scripts/UI/MainMenuUIObject.cs
  Assets/Scripts/UI/MainMenuUIObject.cs.meta
  Assets/Scripts/UI/SettingsMenu.cs
  Assets/Scripts/UI/SettingsMenu.cs.meta
  Assets/Scripts/UI/SliderValueChange.cs
  Assets/Scripts/UI/SliderValueChange.cs.meta
Labels: feature expansion

#98 Finalized Dungeon Generation
  Assets/Scenes/TestDungeon.unity
  Assets/Scripts/World/TestDungeon/CorridorFirstDungeonGenerator.cs
  Assets/Scripts/World/TestDungeon/CorridorFirstDungeonGenerator.cs.meta
  Assets/Scripts/World/TestDungeon/Data/SimpleRandomWalkParameters_Small_Room.asset
  Assets/Scripts/World/TestDungeon/Data/SimpleRandomWalkParameters_Small_Room.asset.meta
  Assets/Scripts/World/TestDungeon/ProceduralGeneration.cs
  Assets/Scripts/World/TestDungeon/RoomFirstDungeonGenerator.cs
  Assets/Scripts/World/TestDungeon/RoomFirstDungeonGenerator.cs.meta
  Assets/Scripts/World/TestDungeon/SimpleRandomWalkDungeon.cs
  Assets/Scripts/World/TestDungeon/TilemapVisualizer.cs
  Assets/Scripts/World/TestDungeon/WallGenerator.cs
  Assets/Scripts/World/TestDungeon/WallTypesHelper.cs
  Assets/Scripts/World/TestDungeon/WallTypesHelper.cs.meta
Labels: new feature, feature expansion

#100 Tile Hover, Work Area Sizing, and Pawn Count
  Assets/Scenes/Ben's Wonderland.unity
  Assets/Scripts/UI/ColonyInfoManager.cs
  Assets/Scripts/UI/GlobalSelection.cs
  Assets/Scripts/UI/UIManager.cs
Labels: new feature, feature expansion

#107 COL 106 - Created EditMode tests for Chest_VM
  Assets/Tests/EditMode/Chest_VM_Test.cs
  Assets/Tests/EditMode/Chest_VM_Test.cs.meta
  Assets/Tests/EditMode/EditMode.asmdef
Labels: unit tests

#108 COL 108 - GlobalStorage_VM Unit Tests + Small change to GlobalStorage_VM
  Assets/Tests/EditMode/Scripts.meta
  Assets/Tests/EditMode/Scripts/Items.meta
  Assets/Tests/EditMode/Scripts/Items/Chest_VM_Test.cs
  Assets/Tests/EditMode/Scripts/Items/Chest_VM_Test.cs.meta
  Assets/Tests/EditMode/Scripts/Storage.meta
  Assets/Tests/EditMode/Scripts/Storage/GlobalStorage_VM_Test.cs
  Assets/Tests/EditMode/Scripts/Storage/GlobalStorage_VM_Test.cs.meta
Labels: unit tests

#109 COL 109 - Tests for Items
  Assets/Scenes/Test Scenes/ItemTests.unity
  Assets/Scenes/Test Scenes/ItemTests.unity.meta
  Assets/Tests/PlayMode/ExamplePlayModeTests.cs
  Assets/Tests/PlayMode/ItemTest.cs
  Assets/Tests/PlayMode/ItemTest.cs.meta
  Assets/Tests/PlayMode/PlayMode.asmdef
  ProjectSettings/EditorBuildSettings.asset
Labels: unit tests

#110 COL 110 - GameClock Test
  Assets/Tests/PlayMode/GameClockTest.cs
  Assets/Tests/PlayMode/GameClockTest.cs.meta
Labels: unit tests

#111 Level Unit Tests
  Assets/Scripts/Managers/Level.cs
  Assets/Scripts/Tiles/BaseTile.cs
  Assets/Scripts/Tiles/StairsTile.cs
  Assets/Tests/EditMode/Scripts/Level/LevelTest.cs
  Assets/Tests/EditMode/Scripts/Level/LevelTest.cs.meta
Labels: unit tests

#112 Pawn and Labor Order Tests
  Assets/Packages/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  Assets/Resources/prefabs/test.meta
  Assets/Resources/prefabs/test/TestGrid.prefab
  Assets/Resources/prefabs/test/TestGrid.prefab.meta
  Assets/Scenes/Test Scenes/EmptyMap.unity
  Assets/Scenes/Test Scenes/EmptyMap.unity.meta
  Assets/Scripts/Animations/AnimatorController.cs
  Assets/Scripts/Managers/GridManager.cs
  Assets/Scripts/Managers/LaborOrderManager.cs
  Assets/Scripts/NPC/Pawn.cs
  Assets/Tests/EditMode/EditMode.asmdef
  Assets/Tests/EditMode/NPC.meta
  Assets/Tests/PlayMode/LaborOrders.meta
  Assets/Tests/PlayMode/LaborOrders/LaborOrderTests.cs
  Assets/Tests/PlayMode/LaborOrders/LaborOrderTests.cs.meta
  Assets/Tests/PlayMode/NPC.meta
  Assets/Tests/PlayMode/NPC/PawnTest.cs
  Assets/Tests/PlayMode/NPC/PawnTest.cs.meta
  ProjectSettings/EditorBuildSettings.asset
  ProjectSettings/EditorSettings.asset
  ProjectSettings/Packages/com.unity.testtools.codecoverage/Settings.json
  ProjectSettings/TimelineSettings.asset
Labels: unit tests
